export const LOADING = 'LOADING'
export const RELATAR_PROBLEMAS = 'RELATAR_PROBLEMAS'
export const RELATAR_PROBLEMAS_SUCESSO = 'RELATAR_PROBLEMAS_SUCESSO'
export const EXISTE_INTERNET = 'EXISTE_INTERNET'